### ISSUE TITLE
"Save and continue" button does not trigger any action

### ISSUE THREAD

**Issue by draciti** [WormBase/afp_webapp#17]
@valearna I am testing here
http://textpressocentral.org:3000/reagent?paper=00049183&passwd=1538698994.3208673&title=Diapause%20is%20associated%20with%20a%20change%20in%20the%20polarity%20of%20secretion%20of%20insulin-like%20peptides.&journal=Nat%20Commun&pmid=26838180

the save and continue button does not seem to work
thx

**Comment by valearna** [comment]
Do you get any error messages? I've tested it here at caltech and it works. It might be a network related problem. I'll do additional testing from other networks.

**Comment by draciti** [comment]
Nope, no error messages. I can Skype if you want to see it 'live'

**Comment by draciti** [comment]
Working now, thanks!
