### ISSUE TITLE
checkboxes from string matching - not svm

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_webapp#2]
populate checkbox for new antibody from cur_strdata

**Comment by valearna** [comment]
cur_strdata contains the following columns: 
cur_paper | cur_datatype | cur_date | cur_strdata | cur_version | cur_timestamp
Which values represent a 'new antibody' in the papers?
I found some papers with 'antibody' cur_datatype but cur_strdata can have several values, e.g., generated antibodies, production Antibody, production antibodies, purified antibody. Which one should we consider?

**Comment by valearna** [comment]
write to afp_antibody table if the paper has 'antibody' with any text

**Comment by draciti** [comment]
Tested, working fine- antibody box no longer checked for this paper. Closing
