### ISSUE TITLE
Check behavior for new author flags for Gene model correction/update

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/afp_webapp#20]
In testing the afp form, if I check the Gene model corrections/updates box on the Overview page, the corresponding structcorr field in the curation status form is not being updated.

Other fields that are similarly not TPC powered, e.g. RNAseq on the Expression page, do seem to be behaving correctly when checked, so I'm not sure why structcorr is not working.

**Comment by valearna** [comment]
@vanaukenk Can you give me the ID of the paper that you marked as Gene model corrections/updates positive in the form?

**Comment by draciti** [comment]
I got the same behavior for WBPaper00053873

**Comment by draciti** [comment]
@vanaukenk paper was WBPaper00050093. there are some comments on the google doc:
https://docs.google.com/document/d/1Q5IqpKuZYQv-8ezUPKsQNP1humtTM92H730AkvD_ReE/edit?ts=5b772087#

**Comment by valearna** [comment]
I've found the bug with the checkbox value. The problem was that the value saved in the DB was always negative. I've tested it for paper WBPaper00053873 and WBPaper00050093 and changed their values to 'positive'. Can you test it on other papers?

**Comment by draciti** [comment]
tested on WBPaper00053739, working fine. Closing
