### ISSUE TITLE
protein activity box flagged positive (should be negative by default)

### ISSUE THREAD

**Issue by draciti** [WormBase/afp_webapp#21]
For WBPaper00053873 protein activity in the Phenotypes and function widget is flagged positive (the box should be negative by default). Not sure if this has anything to do with us messing with the AFP for this paper in the past. Tried to refresh (shift+reload) but could not get a 'fresh' form

**Comment by valearna** [comment]
I used that paper for testing during the Nov 2 call to show you how the 'submit and continue' buttons work and I probably messed up the form. It's a bit complicated to reset the values only for a specific paper. Can you test the same behavior for other papers that have a 'fresh' form?

**Comment by draciti** [comment]
I checked all the other papers for which I had a link and for all of them is negative. If you want me to test on a completely new paper send me the link, otherwise you can close. thx!
