### ISSUE TITLE
add question mark with info about the extraction algorithm

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_webapp#25]
- mention threshold values used

**Comment by valearna** [comment]
Any suggestions for the text to be added @vanaukenk @draciti ?

**Comment by draciti** [comment]
A couple of suggestions depending on where we will put the text. 
Option 1: Adding text in the existing question mark popup: e.g. :Please validate the list go genes in your paper... _Only genes mentioned 2 or more times are extracted._

<img width="482" alt="screen shot 2019-02-21 at 2 12 09 pm" src="https://user-images.githubusercontent.com/901243/53199311-608a4200-35e4-11e9-9e56-dfa487e02cc2.png">

Option 2: Adding text in the 'TPC powered' popup. Could be the same text as above 

<img width="673" alt="screen shot 2019-02-21 at 2 12 17 pm" src="https://user-images.githubusercontent.com/901243/53199415-a47d4700-35e4-11e9-8b07-172a3defa3b5.png">

**Comment by vanaukenk** [comment]
I like Option 1.
It seems intuitive to have the text about thresholds in the ? pop-up.

Thx.

**Comment by draciti** [comment]
agreed

**Comment by draciti** [comment]
this looks good to me, keeping open for @vanaukenk to take a look at
