### ISSUE TITLE
some gk alleles not recognized

### ISSUE THREAD

**Issue by draciti** [WormBase/afp_webapp#26]
For WBPaper00056091:

gk279371- not recognized
gk279385- not recognized
gk473333- not recognized
gk785720- not recognized

while gk333538 was recognized

**Comment by valearna** [comment]
it seems that gk333538 is the only allele present in the postgres table ono_name_variation, which is where we get the list of alleles to be matched

**Comment by draciti** [comment]
ok, could it be that the million mutation project alleles are not all stored in postgres? @vanaukenk do you know? We need to decide if we want to add those as well

**Comment by valearna** [comment]
we need to add some text in the form to say that we are extracting only a subset of gk alleles. We also decided to put a limit on the number of alleles that an author can manually add as free text. Free text alleles should be then automatically added to the autocomplete

**Comment by valearna** [comment]
To be added to the question mark in the allele component: "... only alleles mentioned more than ... were recognized; note that not all the million mutation project alleles are recognized"

**Comment by draciti** [comment]
looks good to me
