### ISSUE TITLE
Genes not extracted -Paper 00056039

### ISSUE THREAD

**Issue by draciti** [WormBase/afp_webapp#28]
hdac-6- synonym of hda-6, 37 mentions
rab-3
myo-3
daf-2

**Comment by valearna** [comment]
hdac-6 was not recognized because gene synonyms were not loaded. This is a bug and it has been fixed in the latest version. I need to run the pipeline again to update the form

**Comment by valearna** [comment]
"rab-3" is converted to "rab 3" (the dash is recognized as a whitespace) in most cases and only one match remains in the original form. This seems a pdf issue since also the 'find' function on my pdf reader fails to find the missing matches. I'm afraid there's not much we can do in this case

**Comment by valearna** [comment]
same problem with myo-3 and daf-2

**Comment by draciti** [comment]
okay- I confirm hdac-6 is extracted now and we will ignore rab-3, myo-3 and daf-2 for the reasons above. Closing
