### ISSUE TITLE
error message when submitting data for paper 56066

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_webapp#34]

**Comment by valearna** [comment]
When trying to calculate MAX(pap_order) for pap_species and pap_genes on empty tables a value None was returned, which was raising an exception when converted to int. Added an additional check to fix the problem.

**Comment by draciti** [comment]
@daniela test this paper and try to submit data. It should not throw an error

**Comment by draciti** [comment]
tested, it does not throw errors. Closing
