### ISSUE TITLE
Split 'Update contact info and lineage' into two separate actions?

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/afp_webapp#36]
On the last page of the form where authors can click a link to 'Update contact info and lineage"
we may want to split this into two separate actions, as there are different forms for each type of information:

Contact info:  https://wormbase.org/submissions/person.cgi

Lineage info: https://wormbase.org/submissions/person_lineage.cgi

Right now, the form just goes to the person_lineage.cgi page.

Also, is each form meant to be pre-populated based on the WBPerson ID of the user?  Right now, when clicking on the link for test papers, there is no data displayed on the resulting page.

**Comment by draciti** [comment]
I agree. 
As side comment: right now when I click on the link I get to a blank page 
<img width="1256" alt="Screen Shot 2019-03-18 at 11 06 13 AM" src="https://user-images.githubusercontent.com/901243/54544540-e2fcec00-496d-11e9-80a3-c9b9904d827c.png">

**Comment by valearna** [comment]
If I'm not wrong the links that @vanaukenk provided are for submitting new data (i.e., to create a new WBPerson), whereas the link that we use in the form points to existing data: http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person_lineage.cgi?action=Display&number=WBPerson1606

The page on tazendra contains both contact info and lineage, so I'm not sure how to split it in two buttons.

I'm updating the form to open the contact page for the logged-in user.

**Comment by valearna** [comment]
Ok, I found that we can pass a parameter to wormbase submission forms with the same format that we use on tazendra. In fact they are probably the same cgi. I will add a button to update contact info

**Comment by valearna** [comment]
ready to test
