### ISSUE TITLE
insert tables for adding new entities

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_webapp#4]
- alleles
- strains
- transgenes

**Comment by azurebrd** [comment]
@valearna Done.

**Comment by valearna** [comment]
thanks @azurebrd. Everything looks good to me. The new react tables are now in the form and they are linked to the new postgres tables. I'm reopening this issue and moving it to "Need testing". @draciti and @vanaukenk I'll wait for your feedback before closing it.

**Comment by valearna** [comment]
@azurebrd can you reopen the issue. For some reason I can't from my account. Thanks!

**Comment by valearna** [comment]
@azurebrd never mind, I was able to reopen it after refreshing the page.

**Comment by azurebrd** [comment]
@valearna Ah, cool cool.

**Comment by draciti** [comment]
thanks both. @valearna : Could you please (pending Kimberly's feedback) 

- [ ] move the new alleles table before the 'allele sequence change' box

- [ ] remove the Publication ID PMID box for Allele, strain, transgenes. We had it for antibody as users were supposed to add antibodies used in previous studies. in this case the new entities are generated in the paper

- [ ] Add greyed out example text for each:
For the  Allele box: e.g. e1000
For the Strain box: e.g. CB1001
For the Transgene box: e.g. ctIs40

**Comment by valearna** [comment]
ready for testing

**Comment by draciti** [comment]
Looks good to me, thanks @valearna. Leaving this open to give a chance to @vanaukenk to test as well

**Comment by valearna** [comment]
@vanaukenk does it look good to you? If so I can close this.

**Comment by draciti** [comment]
looks good to everyone, closing
