### ISSUE TITLE
How often is the pap_gene table updated with AFP genes?

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/afp_webapp#41]
@valearna

How often are the pap_gene tables updated with the final gene list that an author submits?

An author completed submission of genes for WBPaper00056618 yesterday afternoon (PST) but I don't see the genes listed in the paper editor entry for that paper.

Thx.

**Comment by valearna** [comment]
they should be updated as soon as the author completes the submission. I'll check if everything is ok.

**Comment by valearna** [comment]
I found the issue: each time a submission was completed all the new afp-related entries were deleted from pap_gene, also for other papers! I fixed the bug and saved the entries for the 16 submissions that we received so far. Can you check if you see the genes on the paper editor @vanaukenk ?

**Comment by vanaukenk** [comment]
I can see the genes on the paper editor now.  Thanks @valearna !
