### ISSUE TITLE
Use pap_species and pap_species_index tables for afp form autocomplete

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/afp_webapp#5]
Like for the regular expressions, we will want to use the pap_species and pap_species index tables for the species autocomplete on the form.

This will allow the authors to enter species from a much wider list than what is used for curation in the OA.

**Comment by valearna** [comment]
@azurebrd can you modify the API and return species from pap_species_index?

**Comment by azurebrd** [comment]
@vanaukenk Are there any OA fields that would make sense to use the full pap_species list instead of the shorter list the OA configs currently use ?  If not, we'll need to tack that on to some OA.  If any field could use the full list and it would be good to, it'd be easier than creating a fake OA datatype just for querying out through the API.  Also, should it return just the names, or the taxonID + name ?

**Comment by azurebrd** [comment]
@vanaukenk From Karen's email, I'm looking at Engenous_in from the molecule OA, which is using obo_name_ncbitaxonid which has 5966 species, as opposed to pap_species_index which only has 168.  Do you particularly want that subset instead of the full ncbi taxon id set ?

**Comment by azurebrd** [comment]
For now I've added the datatype 'taxonid' to search obo_name_ncbitaxonid off of the molecule OA's endogenousin table.

**Comment by vanaukenk** [comment]
Pasting from my email:

For comparison, I just cross-checked the lists of Caenorhabditis species in the molecule OA vs the paper editor, and the two lists are different (see attached screenshots).

For the paper editor, we initially deliberately chose a subset of possible species that were mostly nematodes and flatworms in order to attach species to incoming papers.

For molecules, the list is obviously much more comprehensive since the curation would require that, but still doesn't look as complete as possible.

I think it would be desirable now to have a single data source for species for all applications and update that on a somewhat regular basis.  I'm assuming that NCBI's taxonomy was the original source for the molecule OA, as it was for the paper editor.

If that's the case, then we should compare what is currently in NCBI taxonomy with what we have in the molecule OA and paper editor tables, make sure we are okay with any potential changes to the information in postgres, then update our species tables, and decide on how frequently we want to check for changes at NCBI.

Also, for AFP we are also using species synonyms, e.g. cow for Bos taurus, so we need to make sure that that information is preserved if/when we update the tables.

<img width="1680" alt="paper_editor_caenorhabditis" src="https://user-images.githubusercontent.com/1730534/45222597-fc1c3600-b282-11e8-9cd1-21d7eb37c5c3.png">
<img width="1680" alt="molecule_oa_caenorhabditis" src="https://user-images.githubusercontent.com/1730534/45222604-fe7e9000-b282-11e8-8bec-2e46078e8863.png">

**Comment by vanaukenk** [comment]
Testing the full NCBI taxon list seems to be too big and slow for optimal performance.
The plan going forward is to use the union of the the paper and oa species listed combined into a single table (?) that can be accessed and used by the paper editor, the OA, and the AFP form.
Will check with Juancarlos wrt setting up this table and working to create a simple editor to add/remove/update entries as needed.

**Comment by valearna** [comment]
we would need the taxon ID to be returned by the API e.g., 
Caenorhabditis elegans ( Taxon ID 6239 )
