### ISSUE TITLE
add question mark to site and time of action

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_webapp#7]
provide more details on when the authors should check the checkbox

**Comment by valearna** [comment]
Site of action: In what tissue is a specific gene to carry out its 
function? This can be demonstrated by phenotype rescue using a 
tissue-specific exogenous promoter, a tissue-specific knock down of gene 
function or other similar experiments. We encourage authors to refer to 
a specific piece of text from their publication in the text box provided.

Time of action: At what time is a specific gene to carry out its 
function? This can be demonstrated by phenotype rescue using a 
lifestage-specific exogenous promoter, a temperature-shift experiment 
with a temperature-sensitive allele or other similar experiments. We 
encourage authors to refer to a specific piece of text from their 
publication in the text box provided.

**Comment by draciti** [comment]
looks good to me, waiting for @vanaukenk feedback before closing
