### ISSUE TITLE
change "anything else?" widget name to "Additional data and comments"

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_webapp#8]
- change title and menu entry
- move update contact info to this widget and move comments to a new widget "Comments and Submit"

**Comment by draciti** [comment]
the explanatory comment in the blue box says: 'In this page you can provide additional information in your paper.' but we are not requesting additional data from the paper in this widget. Think if adding a free text box explicitly asking for additional datatypes that were not identified by us or change the sentence

**Comment by valearna** [comment]
change widget title to "Update contact info and microPublication"
Change help text to "In this page you can update your contact info and submit your unpublished data to microPublication"
